services:
  - type: web
    runtime: docker
    name: m2m
    plan: free
    autoDeploy: true
    envVars:
      - key: PORT
        value: 3001
      - key: HOST
        value: 0.0.0.0
      - key: NODE_ENV
        value: production
